export const readingExplanations: Record<string, string[]> = {
  "rd-001": [
    "The council required the library to remain open during the study.",
    "The method explicitly states that conversations were not recorded.",
    "The passage links the students' location to nearby power sockets. It does not say they preferred sitting with friends.",
    "The signs explained the purpose of shared tables and quiet workspaces.",
    "The team did not treat fewer complaints as sufficient evidence that everyone was satisfied.",
    "Participation was voluntary; payment is not mentioned.",
    "The intermediate area replaced two individual workspaces.",
    "The manager rejected the suggestion to restrict access by age.",
  ],
  "rd-002": [
    "The route was not controlled by a single owner.",
    "The diaries also recorded other modes of transport.",
    "The agreements already in place were one reason this section was chosen.",
    "The passage gives no measured change in property prices.",
    "The device counted passages, so a return trip produced two records.",
    "The council published the limitations of the measurement method.",
    "Different users had different preferences.",
    "The search for funding is described, but no agreement to fund the entire project is reported.",
  ],
  "rd-003": [
    "Returning seeds was voluntary and was not a condition of receiving them.",
    "This information was required on the standard label.",
    "The ages of people donating and receiving seeds are not compared.",
    "Material with unclear labels was set aside rather than distributed immediately.",
    "The organiser asked people to report this kind of experience too.",
    "The organisers explicitly acknowledged that not every participant responded.",
    "The evaluation does not include results from another programme.",
    "Buying additional seeds was allowed when stocks were uneven.",
  ],
  "rd-004": [
    "Checking legal compliance was explicitly excluded from the project's aims.",
    "Written observations came before the audio recording.",
    "The device is mentioned, but its supplier and previous owners are not identified.",
    "No observations were made at night.",
    "Both reactions were retained without giving either priority.",
    "The benches were moved from their original position to a quieter edge.",
    "The passage says nothing about earlier complaints from these people.",
    "A time had to be provided when submitting a recording.",
  ],
  "rd-005": [
    "Success was initially measured by the number of items that worked after repair.",
    "The initial records did not identify intermediate progress separately.",
    "Neither the proportion of returns nor a one-month period is given.",
    "A single record could belong to several categories.",
    "Responding to the follow-up survey was voluntary.",
    "Both methods existed, but their frequency of use is not compared.",
    "The records distinguished between these causes.",
    "Adding overlapping categories would have produced a misleading picture.",
  ],
  "rd-006": [
    "The programme was launched in response to a question visitors repeatedly asked.",
    "Some details had to be reconstructed rather than reproduced exactly.",
    "The passage does not explain how the craftspeople were selected.",
    "The order changed: exploring the object came before the detailed explanation.",
    "Familiarity with the object influenced the response to touching it.",
    "Demonstrations were available, but no numerical comparison of preferences is given.",
    "Changes made to objects for tactile exploration were documented.",
    "The original exhibits remained alongside the replicas.",
  ],
  "rd-007": [
    "The tree's history was spread across several sets of documents.",
    "The historical descriptions were retained.",
    "The passage does not say whether the numbers were physically attached to the trees.",
    "Dates and sources appeared alongside the estimates.",
    "Residents' observations could prompt an inspection.",
    "Payment arrangements are not described.",
    "Decisions still required professional judgement.",
    "Changing the crossing allowed the tree to be preserved.",
  ],
  "rd-008": [
    "The team began by observing how passengers moved around.",
    "Using new participants prevented familiarity with the route from affecting later trials.",
    "No reward or free journey is mentioned.",
    "The ticket-collection symbol was misunderstood, so it was removed.",
    "The old name was retained with additional information.",
    "The passage does not explain how the numbers were chosen.",
    "Testing the actual materials revealed reflections that did not appear on paper mock-ups.",
    "Some questions still legitimately required help from staff.",
  ],
  "rd-009": [
    "The complex did not have a shared reception desk.",
    "Paper records were introduced before software was discussed.",
    "The volunteers' professional experience is not stated.",
    "The revised timetable accommodated people who could not use the original schedule.",
    "These deliveries were excluded.",
    "This result was recorded, although its cause was not fully established.",
    "No conclusions about couriers' working hours are given.",
    "Arranging replacement cover remained the responsibility of project participants.",
  ],
  "rd-010": [
    "Participants told their stories in their own order.",
    "Short descriptions linked topics to positions in the audio recording.",
    "The passage does not confirm that professional typists were involved or that every recording was transcribed.",
    "Access to individual sections could be restricted.",
    "The group retained differing accounts of events.",
    "The exact length of the delay is not given.",
    "Permission documents were stored with the audio and search materials.",
    "Part of the funding was explicitly intended for existing materials.",
  ],
  "rd-011": [
    "Delivery and collection dates had to be coordinated.",
    "Some reported quantities remained provisional estimates.",
    "The passage does not establish that the photographers were former pupils.",
    "There were limits on both cost and capacity.",
    "Rejected doors were no longer advertised as equivalent to the others.",
    "The passage does not specify which workshop project the doors were intended for.",
    "The design was adapted to fit the reused doors.",
    "These two measures were recorded separately.",
  ],
  "rd-012": [
    "This was the stated theme of the exhibition.",
    "The curator rejected this conclusion.",
    "The records described payments, not where the worker lived.",
    "Major repairs were organised differently from routine maintenance.",
    "The letters are explicitly acknowledged as not representing all residents.",
    "There is no comparison of costs or direct link to when the changes were made.",
    "The equipment was retained even after it was no longer used.",
    "Recent memories were not treated as evidence of much earlier practices.",
  ],
  "rd-013": [
    "Early versions of the directions assumed local knowledge.",
    "The versions were similar in length.",
    "The participants' student status or year of study is not given.",
    "A landmark was useful only if it was visible when a route decision had to be made.",
    "The screen hid the object used as a landmark in the original directions.",
    "The passage does not describe whether they asked for help later.",
    "Being memorable did not always make a landmark useful in practice.",
    "A review procedure was established for the published guide.",
  ],
  "rd-014": [
    "The workshop was not intended to choose a competition winner.",
    "The whole text was read before the detailed analysis began.",
    "The translator's publication history is not given.",
    "Participants had different opinions.",
    "Their involvement showed how repetition is perceived when heard aloud.",
    "A reading session is described, but no written test is mentioned.",
    "The group preferred this solution because of the context.",
    "The recording was retained for editorial work.",
  ],
  "rd-015": [
    "The furniture was trialled before a purchase decision was made.",
    "Different classes used the two rooms.",
    "The passage does not describe any payment from the supplier.",
    "Practice reduced the time needed to rearrange the furniture.",
    "Changes were judged by their purpose rather than their frequency.",
    "Not all the old furniture was replaced.",
    "Their specific preference is not stated.",
    "Furniture was ordered only for the selected rooms.",
  ],
  "rd-016": [
    "The photographs differed in both location and date.",
    "Recent cleaning was noted in the visit record.",
    "The source of the cameras is not given.",
    "The method relied on observable features rather than assumptions about sources.",
    "The comparison identified this source of variation.",
    "The paragraph does not identify this particular location or rule out other areas.",
    "Possible influences were discussed without confirming a single cause.",
    "The instructions were published alongside the results.",
  ],
  "rd-017": [
    "No explanation accompanied the attribution.",
    "The document recorded the donor and the date of transfer.",
    "The place of purchase is mentioned, but prices are not compared.",
    "The curator distinguished stronger documentary evidence from weaker evidence.",
    "A similar shape appeared under a different name.",
    "The passage does not say that the specialist visited the museum or examined the object in person.",
    "The revised description was accompanied by supporting images.",
    "References were retained for future researchers.",
  ],
  "rd-018": [
    "Providing advice for real engineering projects was not one of the exhibit's aims.",
    "The limitations were displayed where visitors controlled the model.",
    "The equipment supplier is not named.",
    "The water supply was kept constant while the barrier's position changed.",
    "Incorrect predictions were retained for comparison.",
    "The selection criterion is not given.",
    "The checks revealed physical changes that were otherwise difficult to notice.",
    "The interactive model was retained.",
  ],
  "rd-019": [
    "Human interpretation remained necessary.",
    "Missing data was recorded separately from silence.",
    "The source of funding is not described.",
    "The form allowed uncertainty to be recorded.",
    "Segments not selected by the software were also checked.",
    "There is no comparison of software versions or confirmation that the figure doubled.",
    "Detected calls were not a direct count of animals.",
    "These files were excluded from public playback.",
  ],
  "rd-020": [
    "The room's purpose was not limited to serving the first groups.",
    "Unmet demand was included in the data.",
    "The reasons for cancellations are not given.",
    "An existing booking did not guarantee permanent access.",
    "The noticeboard supplemented electronic messages.",
    "No difference in charges is described.",
    "Practical requirements were considered when allocating rooms.",
    "The committee used several measures rather than occupancy alone.",
  ],
};
